// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH5Vg6-LCCWYsD62IhrPqHOY9ujblBPGc',
    appId: '1:932797512554:web:6c5552b5609f4c33fa8313',
    messagingSenderId: '932797512554',
    projectId: 'notes-firebase-lakshay',
    authDomain: 'notes-firebase-lakshay.firebaseapp.com',
    storageBucket: 'notes-firebase-lakshay.appspot.com',
    measurementId: 'G-CWF5JV1D8Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo3j-Y_woDITi0n_onADXnMC1QN-AxNDI',
    appId: '1:932797512554:ios:4e06b51abc0dc78ffa8313',
    messagingSenderId: '932797512554',
    projectId: 'notes-firebase-lakshay',
    storageBucket: 'notes-firebase-lakshay.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH5Vg6-LCCWYsD62IhrPqHOY9ujblBPGc',
    appId: '1:932797512554:web:e3763a2970d5e972fa8313',
    messagingSenderId: '932797512554',
    projectId: 'notes-firebase-lakshay',
    authDomain: 'notes-firebase-lakshay.firebaseapp.com',
    storageBucket: 'notes-firebase-lakshay.appspot.com',
    measurementId: 'G-4S636CPHW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLjsf1hzqxpFd-EU9tjvEPt-B4347bEjI',
    appId: '1:932797512554:android:74d8805ae1cf29d8fa8313',
    messagingSenderId: '932797512554',
    projectId: 'notes-firebase-lakshay',
    storageBucket: 'notes-firebase-lakshay.appspot.com',
  );

}